name: Build DroidStar Windows

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-windows:
    runs-on: windows-2022

    steps:
      - name: Checkout código
        uses: actions/checkout@v4.2.2

      - name: Instalar Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.0'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw'

      - name: Configurar CMake
        shell: cmd
        run: |
          cd ${{ github.workspace }}
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release

      - name: Compilar
        shell: cmd
        run: |
          cd ${{ github.workspace }}\build
          mingw32-make -j4

      - name: Empaquetar DLLs
        shell: cmd
        run: |
          windeployqt ${{ github.workspace }}\build\DroidStar.exe

      - name: Subir artefacto
        uses: actions/upload-artifact@v4.6.2
        with:
          name: DroidStar-Windows
          path: ${{ github.workspace }}\build\
